---
output:
  word_document: default
  html_document: default
---


|                            | FALSE (N=202372) |  TRUE (N=2273)  | Total (N=204645) | p value|
|:---------------------------|:----------------:|:---------------:|:----------------:|-------:|
|**back_pain_1m**            |                  |                 |                  | < 0.001|
|&nbsp;&nbsp;&nbsp;N-Miss    |       3432       |        0        |       3432       |        |
|&nbsp;&nbsp;&nbsp;FALSE     |  197152 (99.1%)  |    0 (0.0%)     |  197152 (98.0%)  |        |
|&nbsp;&nbsp;&nbsp;TRUE      |   1788 (0.9%)    |  2273 (100.0%)  |   4061 (2.0%)    |        |
|**pain_count_1m**           |                  |                 |                  | < 0.001|
|&nbsp;&nbsp;&nbsp;0         |  197152 (97.4%)  |    0 (0.0%)     |  197152 (96.3%)  |        |
|&nbsp;&nbsp;&nbsp;1         |   3359 (1.7%)    |   448 (19.7%)   |   3807 (1.9%)    |        |
|&nbsp;&nbsp;&nbsp;2         |   1250 (0.6%)    |   641 (28.2%)   |   1891 (0.9%)    |        |
|&nbsp;&nbsp;&nbsp;3         |    408 (0.2%)    |   570 (25.1%)   |    978 (0.5%)    |        |
|&nbsp;&nbsp;&nbsp;4         |    109 (0.1%)    |   380 (16.7%)   |    489 (0.2%)    |        |
|&nbsp;&nbsp;&nbsp;5         |    30 (0.0%)     |   164 (7.2%)    |    194 (0.1%)    |        |
|&nbsp;&nbsp;&nbsp;6         |     7 (0.0%)     |    54 (2.4%)    |    61 (0.0%)     |        |
|&nbsp;&nbsp;&nbsp;7         |     0 (0.0%)     |    16 (0.7%)    |    16 (0.0%)     |        |
|&nbsp;&nbsp;&nbsp;8         |    57 (0.0%)     |    0 (0.0%)     |    57 (0.0%)     |        |
|**pain_count_chrn**         |                  |                 |                  |        |
|&nbsp;&nbsp;&nbsp;0         | 202372 (100.0%)  |    0 (0.0%)     |  202372 (98.9%)  |        |
|&nbsp;&nbsp;&nbsp;1         |     0 (0.0%)     |  1045 (46.0%)   |   1045 (0.5%)    |        |
|&nbsp;&nbsp;&nbsp;2         |     0 (0.0%)     |   718 (31.6%)   |    718 (0.4%)    |        |
|&nbsp;&nbsp;&nbsp;3         |     0 (0.0%)     |   324 (14.3%)   |    324 (0.2%)    |        |
|&nbsp;&nbsp;&nbsp;4         |     0 (0.0%)     |   140 (6.2%)    |    140 (0.1%)    |        |
|&nbsp;&nbsp;&nbsp;5         |     0 (0.0%)     |    38 (1.7%)    |    38 (0.0%)     |        |
|&nbsp;&nbsp;&nbsp;6         |     0 (0.0%)     |    7 (0.3%)     |     7 (0.0%)     |        |
|&nbsp;&nbsp;&nbsp;7         |     0 (0.0%)     |    1 (0.0%)     |     1 (0.0%)     |        |
|&nbsp;&nbsp;&nbsp;8         |     0 (0.0%)     |    0 (0.0%)     |     0 (0.0%)     |        |
|**WBC_v0**                  |                  |                 |                  |   0.023|
|&nbsp;&nbsp;&nbsp;N-Miss    |      12727       |       155       |      12882       |        |
|&nbsp;&nbsp;&nbsp;Mean (SD) |  6.662 (1.539)   |  6.739 (1.571)  |  6.663 (1.539)   |        |
|&nbsp;&nbsp;&nbsp;Range     |  2.300 - 11.200  | 2.600 - 11.170  |  2.300 - 11.200  |        |
|**WBC_v1**                  |                  |                 |                  | < 0.001|
|&nbsp;&nbsp;&nbsp;N-Miss    |      188081      |       424       |      188505      |        |
|&nbsp;&nbsp;&nbsp;Mean (SD) |  6.632 (1.483)   |  6.801 (1.501)  |  6.651 (1.486)   |        |
|&nbsp;&nbsp;&nbsp;Range     |  2.500 - 10.950  | 2.800 - 10.860  |  2.500 - 10.950  |        |
|**neutro_c_v0**             |                  |                 |                  |   0.221|
|&nbsp;&nbsp;&nbsp;N-Miss    |      14026       |       169       |      14195       |        |
|&nbsp;&nbsp;&nbsp;Mean (SD) |  4.059 (1.178)   |  4.090 (1.201)  |  4.059 (1.179)   |        |
|&nbsp;&nbsp;&nbsp;Range     |  0.740 - 7.520   |  1.200 - 7.500  |  0.740 - 7.520   |        |
|**neutro_c_v1**             |                  |                 |                  |   0.003|
|&nbsp;&nbsp;&nbsp;N-Miss    |      188176      |       432       |      188608      |        |
|&nbsp;&nbsp;&nbsp;Mean (SD) |  4.119 (1.155)   |  4.205 (1.177)  |  4.129 (1.158)   |        |
|&nbsp;&nbsp;&nbsp;Range     |  1.000 - 7.680   |  1.400 - 7.390  |  1.000 - 7.680   |        |
|**neutro_p_v0**             |                  |                 |                  |   0.403|
|&nbsp;&nbsp;&nbsp;N-Miss    |      12271       |       135       |      12406       |        |
|&nbsp;&nbsp;&nbsp;Mean (SD) |  60.987 (7.773)  | 60.846 (7.867)  |  60.986 (7.774)  |        |
|&nbsp;&nbsp;&nbsp;Range     | 39.250 - 82.800  | 39.670 - 82.400 | 39.250 - 82.800  |        |
|**neutro_p_v1**             |                  |                 |                  |   0.069|
|&nbsp;&nbsp;&nbsp;N-Miss    |      187979      |       397       |      188376      |        |
|&nbsp;&nbsp;&nbsp;Mean (SD) |  62.398 (8.138)  | 62.033 (8.419)  |  62.356 (8.171)  |        |
|&nbsp;&nbsp;&nbsp;Range     | 39.500 - 86.100  | 39.600 - 85.200 | 39.500 - 86.100  |        |
|**age**                     |                  |                 |                  |   0.291|
|&nbsp;&nbsp;&nbsp;N-Miss    |       5233       |       23        |       5256       |        |
|&nbsp;&nbsp;&nbsp;Mean (SD) |  56.774 (8.021)  | 56.594 (7.658)  |  56.772 (8.017)  |        |
|&nbsp;&nbsp;&nbsp;Range     | 39.000 - 73.000  | 40.000 - 70.000 | 39.000 - 73.000  |        |
|**sex**                     |                  |                 |                  |   0.271|
|&nbsp;&nbsp;&nbsp;N-Miss    |       5233       |       23        |       5256       |        |
|&nbsp;&nbsp;&nbsp;F         |  103195 (52.3%)  |  1204 (53.5%)   |  104399 (52.4%)  |        |
|&nbsp;&nbsp;&nbsp;M         |  93944 (47.7%)   |  1046 (46.5%)   |  94990 (47.6%)   |        |
|**ethnicity**               |                  |                 |                  |   0.329|
|&nbsp;&nbsp;&nbsp;N-Miss    |      143645      |      1612       |      145257      |        |
|&nbsp;&nbsp;&nbsp;ASIAN     |    957 (1.6%)    |    6 (0.9%)     |    963 (1.6%)    |        |
|&nbsp;&nbsp;&nbsp;BLACK     |    703 (1.2%)    |    5 (0.8%)     |    708 (1.2%)    |        |
|&nbsp;&nbsp;&nbsp;MIXED     |    250 (0.4%)    |    4 (0.6%)     |    254 (0.4%)    |        |
|&nbsp;&nbsp;&nbsp;OTHER     |    579 (1.0%)    |    9 (1.4%)     |    588 (1.0%)    |        |
|&nbsp;&nbsp;&nbsp;WHITE     |  56238 (95.8%)   |   637 (96.4%)   |  56875 (95.8%)   |        |
